### ISSUE TITLE
Fix .dockerignore

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/invoice#1]
![image](https://cloud.githubusercontent.com/assets/22681804/25005946/44f5bf10-205b-11e7-8a4a-df889838a28d.png)

Build context is huge, this looks like we are seding a lot a data to the buildcontext that isnt needed

**Comment by gr4per** [comment]
It is due to node_modules not included in .dockerignore

**Comment by dzhitomirsky-sc** [comment]
Done.
