### ISSUE TITLE
When user approves/inspects/sets to clarification (or cancels actions) the invoice, success note should be shown for a while.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#102]

**Comment by pirttpi1** [comment]
![invoiceapprovednotification](https://user-images.githubusercontent.com/31001609/29860304-5e0045c2-8d6e-11e7-93c0-4279c8c696e6.PNG)

The text is depending of the action:
'Invoice approved successfully!'
'Invoice reviewed successfully!'

**Comment by dzhitomirsky-sc** [comment]
Added alerts in way, described in issue header. Please, test is.

**Comment by pirttpi1** [comment]
This is ok now!
