### ISSUE TITLE
Invoice list modifications

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#103]
All the headers should be removed (payer company, supplier name and so on)

![no_headers](https://user-images.githubusercontent.com/31001609/29858161-d1fa79fc-8d64-11e7-9715-fbffb40ab2f4.PNG)

Comment and clarification icons will be like in this picture, as well the due date indicator (which will be added with other Issue)

Due date should be format dd.mm.yyyy

**Comment by pirttpi1** [comment]
This change should be done to 'My tasks' and 'Processed'

**Comment by alevchuk-sc** [comment]
Implemented. Please test.

**Comment by pirttpi1** [comment]
Supplier code should be supplier name.
We talk about this date and regional settings maybe with another issue later.

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 , showing supplier name is the scope of #97

**Comment by pirttpi1** [comment]
Yes. So this is ok.

**Comment by pirttpi1** [comment]
One more thing: the amount should be in 2 decimals. 
So not like 200 EUR, or 200.1 EUR.

**Comment by pirttpi1** [comment]
This is ok now!
