### ISSUE TITLE
Due date indicators should be added to the invoices 'my task list':

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#104]
When due date is current date or tomorrow, we want to show the notification:
![indicator_icons_notification_alert](https://user-images.githubusercontent.com/31001609/29858337-b92c5d7c-8d65-11e7-9cc4-4b51702ba866.png)
When do date is older than current date, the notification
![indicator_icons_notification_error](https://user-images.githubusercontent.com/31001609/29858345-c840d2ca-8d65-11e7-9182-a14b0754b536.png)
should be shown.

**Comment by dzhitomirsky-sc** [comment]
Done. Please, test it.

**Comment by pirttpi1** [comment]
Both icons are shown correctly.

**Comment by dzhitomirsky-sc** [comment]
Closed.

**Comment by pirttpi1** [comment]
The icons should be shown only in 'my tasks'-view, not processed.

**Comment by alevchuk-sc** [comment]
Implemented. Please test.

**Comment by pirttpi1** [comment]
This is ok now.
