### ISSUE TITLE
All invoices grid and fields shown there.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#105]
In 'all invoices' grid all the invoices are shown, and the needed fields are:
o	Company name
o	Supplier name
o	Due date
o	Gross amount
o	Currency
o	Invoice number
o	Order number

**Comment by dzhitomirsky-sc** [comment]
I've added grid view for all invoices. Please check it out. May be we should style it a little bit?

**Comment by pirttpi1** [comment]
Just something small to say:
Customer Name -> Company name
Supplier Name -> Supplier name
Due Date -> Due date
Gross Amount -> Gross amount
Invoice Number -> Invoice number
Order number is missing (so we could add it, even though there's no value yet.)

Otherwise list looks ok.

**Comment by pirttpi1** [comment]
Now it's ok.
