### ISSUE TITLE
Inspection related changes (inspect -> review)

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#106]
Inspection related words are changed to Review, like:
Inspect -> Review
Inspection -> Review
Inspection required -> Review required
Cancel inspection -> Cancel review

**Comment by alevchuk-sc** [comment]
Updated. Please test.

**Comment by pirttpi1** [comment]
This is ok now!

**Comment by dzhitomirsky-sc** [comment]
Closed.
