### ISSUE TITLE
Sorting default with due date is different in different invoice lists.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#109]
My task list: The oldest date first,
Processed list: The newest date first.

**Comment by pirttpi1** [comment]
Supplier sorting needs to be by supplier, not supplierId

**Comment by alevchuk-sc** [comment]
Updated. Supplier sorting is fullfilled by supplier name.

**Comment by pirttpi1** [comment]
Sorting is done correctly with the due date. Supplier sorting was changed to the code, but testing was not very good, because there is only two suppliers on the invoices and they have supplier code and name in the same order However with these two, it worked ok..
