### ISSUE TITLE
Integrate new menu into application

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#111]
![image](https://user-images.githubusercontent.com/24652264/29916270-eeb93cb2-8e46-11e7-9254-055e44334c49.png)
Under My Invoices  are ‘My tasks’ and ‘Processed’

**Comment by pirttpi1** [comment]
Check the latest specs from Paris OCI UI concept - v4 (google drive)

**Comment by dzhitomirsky-sc** [comment]
Please, check it out.

**Comment by pirttpi1** [comment]
ok
