### ISSUE TITLE
When user sets invoice in clarification, the default is 'Cancel status'

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#122]
![image](https://user-images.githubusercontent.com/31001609/30014317-4b2f16d2-9154-11e7-88db-bcbec83f09ea.png)

**Comment by pirttpi1** [comment]
The text in the tab 'Cancel status' is 'Clarification'.

**Comment by dzhitomirsky-sc** [comment]
Fixed, please check it out.

**Comment by pirttpi1** [comment]
This is ok now.
