### ISSUE TITLE
When user approves/review ths invoice, the UI shows the invoices without comment/tab part for a moment.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#127]
![approving](https://user-images.githubusercontent.com/31001609/30054628-590b70f2-9235-11e7-9b06-bc113c456b1f.PNG)

This shouldn't change like this.

**Comment by alevchuk-sc** [comment]
Fixed. Now empty block is displayed during invoice details loading.

**Comment by pirttpi1** [comment]
This looks ok now.
