### ISSUE TITLE
Matching: UI for item level matching

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#131]
![image](https://user-images.githubusercontent.com/24652264/30068231-c7115762-9265-11e7-9be6-9cd1eb774238.png)

**Comment by pirttpi1** [comment]
This is still in progress.

**Comment by pirttpi1** [comment]
Ilkka is already doing this, but I will write this down. 
All the amounts need to be shown with 2 decimals (123.00). Unit price should be with 6 decimals, so if you like you can change it already to the UI.
Matching difference is still not done.

**Comment by pirttpi1** [comment]
On invoice rows and matching items we should see the needed decimals (unmatched view)
![image](https://user-images.githubusercontent.com/31001609/31701560-e8da5962-b3d9-11e7-95f5-12b93b634fc6.png)

**Comment by pirttpi1** [comment]
This six decimal thing will be checked with #243. Otherwise ok.
