### ISSUE TITLE
View modes of My invoices to top of the invoice list

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/invoice#141]
Remove dropdown (My tasks, Processed) menu from My invoices -navigation panel item. And, those two view modes are added to top of invoice list by underlining the selected one.
![view modes](https://user-images.githubusercontent.com/31068341/30201252-b71efdb8-9482-11e7-9c92-54ff94e13093.PNG)

**Comment by dzhitomirsky-sc** [comment]
Please, test it.

**Comment by pirttpi1** [comment]
My Tasks should be My tasks

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 Refactored labels - please check it out.

**Comment by pirttpi1** [comment]
Ok, there's two more labels, but i asked Aappo to change them.
