### ISSUE TITLE
User menu in navigation panel

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/invoice#142]
It is a rightmost item in a first row of navigation panel, which displays the first name of the user and small arrow for floating menu indication. User menu content is
- Andy or Indy picture (later on displays the initials of first and last name if there is no picture)
- Name of the user, and username below that
- Logout action icon
- Action links (My services, Settings, Help). Link font colour was Petrol (#006070)
- Light horizontal separation line
- Dropdown component for changing a language 
![user menu](https://user-images.githubusercontent.com/31068341/30204911-c954f1ba-948f-11e7-99e4-2f6a6df2d147.PNG)
Logout icon:
![logout_icon](https://user-images.githubusercontent.com/31068341/30204925-e024b47a-948f-11e7-96af-c216c0c2906c.png)
Pictures of Andy and Indy:
![andy pic](https://user-images.githubusercontent.com/31068341/30204950-f1c1772c-948f-11e7-90d9-9d65f39c8d53.png)
![indy pic](https://user-images.githubusercontent.com/31068341/30204956-fa99f914-948f-11e7-848f-9f1f9df9c382.png)

**Comment by pirttpi1** [comment]
ok.
