### ISSUE TITLE
IDs for elements need to be added. 

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/invoice#151]
For test automation ids for elements are needed. Here is an example of the ids that are needed. 
![image](https://user-images.githubusercontent.com/31001652/30369655-eb48717e-987d-11e7-8886-7318a7946040.png)
For dynamic elements the ids might be harder to add, but please try the best you can. For the invoices in my tasks list it would help if the boxes would have an id like listItem_invoiceId, so then it would be possible to find the content of the box.

**Comment by blomqsu1** [comment]
ok

**Comment by jluukka** [comment]
Modifying IDs in matching view to better represent information found on screen

**Comment by jarkinn** [comment]
While creating test automation cases I noticed two places where the IDs could be added:
- invoice-grid-action-panel in Invoices overview (buttons at least, if not possible to add for drop-down menu items)
- Check-boxes in Matching -> Matched view

**Comment by blomqsu1** [comment]
Current IDs are usable. Closing issue.
