### ISSUE TITLE
Add purchaseOrderId to PurchaseInvoice model

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#154]
Add  purchaseOrderId STRING(50) to PurchaseInvoice model for matching purposes.

We need Purchase Order number information also in invoice header level, not only in line item level. 

case 1: we don't have invoice line items (for example scanned invoices) at all, but we still want to do matching against PO/GR data, so source matching candidate data (=PO number) must be found from the invoice header level.
case 2: we define that we will use both PO number from invoice header level and from invoice line item level (looks to be the most common way to define matching candidate query currently)

**Comment by dzhitomirsky-sc** [comment]
Done.
