### ISSUE TITLE
Add demo data for manual matching, invoice and matching data

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#169]
Take a look at the attached Excel file:
1. There are 3 invoices and line items for them. 
2. There are 3 different Purchase Orders with their line items 
- the first PO has a bit more  information about the fields etc. in the 2nd sheet of the file.
3. Add also posting data to related invoice line items
[Project Paris Matching data.xlsx](https://github.com/OpusCapita/invoice/files/1310624/Project.Paris.Matching.data.xlsx)

Please, ask help if Excel isn't giving all needed information about the data items.

**Comment by TimoRiippa** [comment]
Here is an advanced version of the data including 1st invoice and related matching data + invoice PDF images. Attach correct PDF to an invoice by checking the invoice number.
[201710019-Musterkunden-AG.pdf](https://github.com/OpusCapita/invoice/files/1313886/201710019-Musterkunden-AG.pdf)
[201710020-Musterkunden-AG.pdf](https://github.com/OpusCapita/invoice/files/1313884/201710020-Musterkunden-AG.pdf)
[201710021-Musterkunden-AG.pdf](https://github.com/OpusCapita/invoice/files/1313885/201710021-Musterkunden-AG.pdf)
[Project Paris Matching data.xlsx](https://github.com/OpusCapita/invoice/files/1313883/Project.Paris.Matching.data.xlsx)

**Comment by alevchuk-sc** [comment]
Demo data is added. 
Demo invoices could already be checked on the service UI or through corresponding rest endpoints. But here's no such possibility for matching related data currently so we should wait till it's ready.

**Comment by pirttpi1** [comment]
The second invoice with PO Number O161261197, first line item:
Total with VAT, and Total with VAT and discount should be 730,66, 
Total and Total with discount should be 614 eur.

**Comment by pirttpi1** [comment]
And about this matching data, is there data for O161261199, O161261197 and O16126198?

**Comment by alevchuk-sc** [comment]
> Total and Total with discount should be 614 eur.
Updated.
> And about this matching data, is there data for O161261199, O161261197 and O16126198?
There is no matching demo data currently. We will add it when matching functionality is available.

**Comment by pirttpi1** [comment]
Ok, I thought the matching data was there already, but we just can't check it with UI. So, this has to wait that time? I'll check the line item amount.

**Comment by pirttpi1** [comment]
The invoice line item is now ok, so just waiting for matching data.

**Comment by pirttpi1** [comment]
Demo matching data is still missing for two invoices. 
orderItemNo has always 1, should be 1,2,3..

**Comment by alevchuk-sc** [comment]
> Demo matching data is still missing for two invoices.

Working on it.

**Comment by alevchuk-sc** [comment]
> Working on it.

Updated. Please test.

**Comment by TimoRiippa** [comment]
Looks good now, thanks!
