### ISSUE TITLE
Add Line items tab to My Invoices and Matching views which has a grid containing invoice line items 

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#171]
These columns with corresponding data should be shown in the grid in this default order (model field = column name):

orderItemNo = Line #
purchaseOrderId = PO number
productDescShort = Product
productId = Product Id
quantityCharged = Charged
quantityOrdered = Ordered
quantityDelivered = Delivered
unitOfMeasureId = UOM
netPrice = Net price 
grossPrice = Gross price
totalNetPriceDiscounted = Total, with discount
totalGrossPriceDiscounted = Total, with VAT & discount
totalNetPrice = Total
totalGrossPrice = Total, with VAT
vatPercentage = VAT %
orderReference = Order reference
orderDate = Order date
deliveryNoId = Delivery note

Line items tab should be place between Details and Posting tab.

**Comment by dzhitomirsky-sc** [comment]
Please, check it out.

**Comment by pirttpi1** [comment]
@dzhitomirsky-sc This looks ok otherwise, but should we have the alignment right on the numerical fields?

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 ,I will create additional task for it.

**Comment by pirttpi1** [comment]
@dzhitomirsky-sc Posting is ok already, line items are not.

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 I've updated numeric data align for Items grid and invoice grid and changed Order Number filed in Invoice grid to PO number. Please check it out.

**Comment by pirttpi1** [comment]
One more comment: the tab name should 'Line items'

**Comment by dzhitomirsky-sc** [comment]
Changed label to 'Line items'.

**Comment by pirttpi1** [comment]
This is ok now.

**Comment by pirttpi1** [comment]
@Aappo: these should be translated.

**Comment by Aappo** [comment]
They are translated, in Pull request 182. Although, I would change Line # into Line No./Rivinro

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 , Is it anything to be done regarding this issue?

**Comment by pirttpi1** [comment]
@dzhitomirsky-sc I'm still waiting for the pull request 182.

**Comment by pirttpi1** [comment]
This is ok now.
