### ISSUE TITLE
UI changes: empty page & test notifications

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#173]
TODO:
* changes empty layout like in the screenshot
* add mock notifications like it is done on react-navigations test-page.
<img width="1440" alt="2017-09-19 11 11 53" src="https://user-images.githubusercontent.com/24650360/30582170-6c370d20-9d2b-11e7-8480-a08abb30570e.png">

**Comment by pirttpi1** [comment]
Ok.
