### ISSUE TITLE
Functionality for match and unmatch buttons

### ISSUE THREAD

**Issue by huukias** [OpusCapita/invoice#177]
When pressing match button:
- Add rows from matched items to PurchaseInvoice2MatchingDocument table.
- Matched items will be removed from the unmatched view and will be available to matched view.
- Next invoice row is selected automatically and the best candidate is automatically selected and the first one on the list.

When pressing unmatch button:
- Remove rows of selected items from PurchaseInvoice2MatchingDocument table.
- Matched items will be removed from the matched view and will be available to unmatched view.
- Next invoice row is selected automatically and it's matched row is automatically selected.

**Comment by TimoRiippa** [comment]
Looks to work as expected.
I would like to know exactly what happens under the hood i.e. in the field level changes etc.

**Comment by pirttpi1** [comment]
When pressing unmatch button, this is not happening:
Next invoice row is selected automatically and it's matched row is automatically selected.

**Comment by pirttpi1** [comment]
ok.
