### ISSUE TITLE
UI texts missing from .json

### ISSUE THREAD

**Issue by Aappo** [OpusCapita/invoice#184]
Some UI texts still need to be added to the .json files, so they can be localized:

- The orange "Matching" button in the Matching view
- The title "Comments" on the Comments data card on the Invoice details tab
- The word "Comment" in empty commenting text fields, that gets replaced by the actual comment
- The word "Search" in the search field in the top navigation bar
- The In Clarification icon's tool tip in the My invoices view

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 All keys, except 5th are added (or they already existed). Regarding 5th one - the was never such kind of tip, please clarify.

**Comment by pirttpi1** [comment]
@dzhitomirsky-sc, there' seems to be this tooltip:
![image](https://user-images.githubusercontent.com/31001609/31325592-64b7a5cc-acc7-11e7-87c4-63e97cc46527.png)

**Comment by dzhitomirsky-sc** [comment]
This comment is an internal part of [react-icons](https://raw.githubusercontent.com/OpusCapita/react-icons/master/images/indicators/StatusInclarification.svg) svg element.

**Comment by pirttpi1** [comment]
@Aappo : Now you can add translations to these. (Card_Status_inclarification copy will be removed)

**Comment by dzhitomirsky-sc** [comment]
1)MyTaskList.label.matching
2)Details.comments.title
3)Action.comment.placeholder
4)Navigation.search.placeholder

**Comment by pirttpi1** [comment]
Ok.
