### ISSUE TITLE
App selection menu improvements

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#190]
App Name: current Product/Module/Technical Service
sorted/grouped!

3 items per row
-----------------
1. Row
Shop: OPC
Order (not clear if that works, alternative: Purchase Orders): PROC
Invoice: OCI

2. Row
Inventory: Inventory/INVT
Analytics: some functions from current PROC, new functionality not ready yet

3. Row
RfQ: RfQ
Supplier Information: Supplier Information Manager/SIM
Contracts: no functionality yet

4. Row
Receivables Collection: unknown
Payments: unknown
Liquidity: unknown

5. Row
Business Network Portal: Business Network Portal
Catalog Portal: Self Service Manager/SSM
Document Portal: Supplier Document Portal/SDP

6. Row
Product Information: Produt Information Manager/PIM

Use the same app icons as on [demo](https://opuscapita.github.io/react-navigation) page.

URLs to applications should be stored in Consul as key-value pairs.
E.g. OPC=http://test.jcatalog.com/dev-proc/opc

In case URL for the selected application is not configured, show alert message:
> Application is not available

**Comment by dzhitomirsky-sc** [comment]
Reimplement application grid acording [the latest ui spec](https://docs.google.com/presentation/d/16qIgbJCBOzxpoH6aTr2F1VA7FAi9l8cHAEuN3-e5ER8/edit#slide=id.p4). Please check it out.

**Comment by pirttpi1** [comment]
There's scroll bar problem with Firefox at least.
![image](https://user-images.githubusercontent.com/31001609/31270235-2ae3070c-aa8c-11e7-9e86-80424f94c6d0.png)

**Comment by pirttpi1** [comment]
This is ok.
