### ISSUE TITLE
Active tabs should be shown correctly.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#205]
1. User selects Matching tab -> User selects Matching-button -> Matching tab should be active, not Import.
![import](https://user-images.githubusercontent.com/31001609/31072620-475fdd56-a771-11e7-8218-ff02ff823b5c.PNG)

2. User selects Import, Invoices -> Import should be active, not 'My invoices'.
![my_invoices](https://user-images.githubusercontent.com/31001609/31072665-7b8f50ac-a771-11e7-8f19-a173d7b1fc0a.PNG)

**Comment by alevchuk-sc** [comment]
Fixed. Please test.

**Comment by pirttpi1** [comment]
This is ok now.
