### ISSUE TITLE
Matching - selected invoice should be kept as selected when returning from matching view

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#206]
Short description: 
Keep selected Invoice as selected one when jumping between invoice list and matching view as far as the invoice isn't fully matched and should be removed from the list. If the invoice is fully matched and removed from the invoice list then the next invoice in list order should be selected (not the first one).
------------------------
use case/how to reproduce the current problem/situation:
1. Select 3rd invoice from the invoice list and press Matching button --> move to Matching view
2. Go back to Invoice list for example to see invoice image of the selected invoice
3. Currently always the first invoice in the list is selected, not the invoice what has been handled and 
what's invoice image would like to be seen.
-----------------
How should work:
1. When invoice list is opened in matching the first time then the first invoice is selected
2. When a user presses "back" arrow button from matching functionality then always the previously selected invoice should be selected from the invoice list if it still exists there. If not then the next invoice from the already handled invoice.

**Comment by pirttpi1** [comment]
I think this is not working. If I select the third invoice and go to matching and back, the invoice is selected on the left, but the invoice information is from the first one on the list.

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 Fixed, please test it.

**Comment by TimoRiippa** [comment]
This works now as expected, selected invoice from the list is shown when went back from the matching to invoice list.
