### ISSUE TITLE
Use new OC favicon also in Invoices

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/invoice#208]
If having any questions contact to Maarit Mannonen. Attached icon has to be zipped because this tool doesn't not accept ico-file format.
[OC_favicon_16x16.zip](https://github.com/OpusCapita/invoice/files/1351366/OC_favicon_16x16.zip)

**Comment by dzhitomirsky-sc** [comment]
Please check it out.

**Comment by pirttpi1** [comment]
Ok.

**Comment by pirttpi1** [comment]
It is ok with IE and Chrome, but with Firefox, it,s ok in the tab:
![image](https://user-images.githubusercontent.com/31001609/31119808-eaab7dde-a83a-11e7-93de-24c32de25122.png)
But should it be also in the favorite bar:
![image](https://user-images.githubusercontent.com/31001609/31119853-0a61af22-a83b-11e7-92ed-a81f4b0be3b4.png)

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 Please clean up firefox cache.

**Comment by pirttpi1** [comment]
Finally, it's ok.
