### ISSUE TITLE
Create hidden url to reset demodata

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#224]
TODO:
* url endpoint should be hidded (no button on ui to call it)
* GET /invoice/api/demodata/reset
* it should clear all data from db except those items that exist in /db/migrations/data
* auto increment IDs (SNs) should stay the same - it can potentially break posting.

**Comment by alevchuk-sc** [comment]
Implemented. Please test.

**Comment by pirttpi1** [comment]
Ok. Now even matching is reset.
