### ISSUE TITLE
Finalize the Invoices’ main navigation items

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/invoice#226]
Navigation view item should be in following order
- My invoices
- All invoices
- Workflow
- Matching
- Purchase orders
- Contracts
- Settings

![invoices navi items](https://user-images.githubusercontent.com/31068341/31427412-d265b132-ae6f-11e7-8c65-5148d8a717e1.PNG)

**Comment by dzhitomirsky-sc** [comment]
@alevchuk-sc I addition please migrate to the latest version of react-navigation.

**Comment by pirttpi1** [comment]
Is it possible to have 'import'-tab back to development version after release version? Just for making my testing easier? However it should be removed from the release.

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 OK we will hide it for next week.

**Comment by alevchuk-sc** [comment]
Updated. Import tab is visible only for user with "customer-admin" role (f.e. john.doe@ncc.com).

**Comment by pirttpi1** [comment]
This is ok.
