### ISSUE TITLE
Matching view - enable selecting only one item, calculate difference

### ISSUE THREAD

**Issue by ilkkalehtinen** [OpusCapita/invoice#241]

**Comment by pirttpi1** [comment]
When matched the 3rd Invoice line item from the list the 2nd item is selected with check-box and Matching candidates are fetched for that, but the yellow square is around the 4th item. 
How it should work: 4th item should be selected with check-box and matching candidates for it.

**Comment by pirttpi1** [comment]
This seems ok now.
