### ISSUE TITLE
Matched view enhancements

### ISSUE THREAD

**Issue by ilkkalehtinen** [OpusCapita/invoice#254]
-there should be data also for PO items in columns, now only PO number has data (critical priority)
-Indent PO so that it is easier to see that it is below INV. (high priority)
-Decimals missing if 25 EUR à 25.00 EUR is the correct way (medium priority)
-Unmatch button would be better in left corner instead of the current right cornet, too far away from the line selection (medium priority)
-Matching difference amount is not updated after unmatch button is pressed (medium priority)

**Comment by pirttpi1** [comment]
These enhancements are ok!
