### ISSUE TITLE
Implement standard invoice approval flow

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#27]
Implement standard invoice approval flow that includes two manual steps Inspection and Approval which can be accessed by users with roles INSPECTOR and APPROVER correspondingly.
Available actions on step Inspection are Inspect and Set to Clarification, Approval - Approve and Set to Clarification.
On each step user can leave a comment which will be currently saved in one text field invoice.comment.
Information about current assignee should be saved in invoice.assignee field.

**Comment by dzhitomirsky-sc** [comment]
Done in #38 PR.
