### ISSUE TITLE
Implement automatic matching for invoices, imported from eProc

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#270]
**Info**
When the invoice is imported from eProc side after PO-flip to invoice it should be matched automatically.

**TODO**
* Use already existing SimilarityTool to find MatchingDocument Items with 100% 
* Do it after successful invoice import with existing PO id
* Emulate matching process automatically (create PO2MD mappings and and calculate required Matching statuses and MatchedOn Dates )

**Comment by pirttpi1** [comment]
Invoice is imported and matching is done. Invoice image is still missing, but not part of this issue.
