### ISSUE TITLE
IE problems 

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#273]
Users can't change the tabs correctly:
![image](https://user-images.githubusercontent.com/31001609/31815634-eb55a288-b595-11e7-8547-9d7151e3a806.png)

This does not look good:
![image](https://user-images.githubusercontent.com/31001609/31815658-0142a190-b596-11e7-8489-91d001f119cc.png)

The buttons aren't normally on the left side, they are in the middle. (Check with other browsers)
![image](https://user-images.githubusercontent.com/31001609/31815708-2ad939ec-b596-11e7-8bf0-227b468035f8.png)

**Comment by dzhitomirsky-sc** [comment]
@alevchuk-sc , while doing this please involve @kvolkovich-sc to fix react-navigation to fix navigation markup under IE and possibly to assist fixing css layout of buttons and tabs. Check tabs everywhere they are used ('doing' class)

**Comment by dzhitomirsky-sc** [comment]
Fixed. Please test it.

**Comment by pirttpi1** [comment]
This is ok now.
