### ISSUE TITLE
Matching is done quickly from UI.  -> matches wrong PO items.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#277]
User opens matching and starts making matching one by one, by clicking quite fast.
The result is totally odd. Sometimes invoice item is combined to already matched item, or the invoice item is marked matched, but not combined anywhere (however, PO-items are all matched).
But if you do it very slowly and wait for every action finish correctly, it might go just fine.

**Comment by pirttpi1** [comment]
I still have problems. Rows are added without PO, even though it was selected. Matching button is disabled suddenly and can't match/unmatch anymore without refresh.

**Comment by ilkkalehtinen** [comment]
Buttons are now disable until candidates is loaded.

**Comment by pirttpi1** [comment]
This look good now.l
