### ISSUE TITLE
Add more columns to All Invoices view

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#286]
Add more columns to All Invoices view:
- status
- matching status
- matching type

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 When testing these, please also check out Invoice and Invoice items grids - it was migrated to another library (react-table).

**Comment by pirttpi1** [comment]
When invoices were imported from the eproc -> Status is InvoiceGrid.status.null.label

**Comment by apechenko-sc** [comment]
Values in column Invoice number should be left aligned.

**Comment by pirttpi1** [comment]
Sorting does not work with Finnish user.

**Comment by dzhitomirsky-sc** [comment]
Fixed both Anatoly's and Pia's improvements. Please check it out.

**Comment by pirttpi1** [comment]
Btw, were we supposed to have matchedOn date as well?

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 We have this field in the db model, but there were no requirement/issue to add it to 'All Invoices' view. If it makes cense - lets do it - it is not a hard thing.

**Comment by pirttpi1** [comment]
@dzhitomirsky-sc I think the date was in some of the UX designs, but not here in this issue. So should I make the new one, or just add the enhancement here.

**Comment by pirttpi1** [comment]
This issue is ok, created a new issue related to matched on date.
