### ISSUE TITLE
Incorrect totalNetPriceDiscounted value for incoice item imported from Procurement

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#287]
In current implementation totalNetPriceDiscounted value equals to totalGrossPriceDiscounted, which is wrong in general. In case item doesn't have a discount, totalNetPriceDiscounted should equal to totalNetPrice.

**Comment by dzhitomirsky-sc** [comment]
in proc domain model in TransactionItem there are 3 fields responsible for discounts:
* Boolean isDiscounted
* BigDecimal percentageDiscount
* BigDecimal absoluteDiscount

In our case during import we should do the next:
* if eProcInvoice.isDiscounted -> purchaseInvoice.totalGrossPriceDiscounted = purchaseInvoice.totalGrossPrice - eProcInvoice.absoluteDiscount
* if eProcInvoice.isDiscounted -> purchaseInvoice.totalNetPriceDiscounted = purchaseInvoice.totalNetPrice - eProcInvoice.absoluteDiscount

P.S.
Reflect these changes in unit test.

**Comment by alevchuk-sc** [comment]
Fixed. Please test.

**Comment by pirttpi1** [comment]
Now the amounts were ok.
