### ISSUE TITLE
Add Rejected state to Invoice flow

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#296]
Add Rejected state to Invoice flow based on the attached document.
[OCI Approval flow - v1.pptx](https://github.com/OpusCapita/invoice/files/1421072/OCI.Approval.flow.-.v1.pptx)

**Comment by alevchuk-sc** [comment]
Implemented. Please test.

**Comment by pirttpi1** [comment]
This works ok, but Rejection should be after Commenting, like the spec says:
![image](https://user-images.githubusercontent.com/31001609/33130508-463ba68c-cf9c-11e7-9006-7b60bf7bb4a1.png)

**Comment by alevchuk-sc** [comment]
>This works ok, but Rejection should be after Commenting, like the spec says:

Updated. Please test.

**Comment by pirttpi1** [comment]
This is now ok!
