### ISSUE TITLE
Backend for saved views in All Invoices

### ISSUE THREAD

**Issue by huukias** [OpusCapita/invoice#301]
Make backend queries for all invoices page.

These include:
- Show invoices which are fully matched
- The same as above and but with parameter (automatically or manually matched)

**Comment by dzhitomirsky-sc** [comment]
@huukias Basic  */api/invoices* endpoint is done using epilogue, so it supports default querying with exact matching. It means that request like **/api/invoices?matchingStatus=Fully _should_ work out of the box. For more info check [filtering](https://github.com/dchester/epilogue) section of epilogue docs. If it works it may save some implementation time.

**Comment by huukias** [comment]
Tested this and you are correct 
api/invoices?matchingStatus=Fully 
seems to find all fully matched invoices. 

So manually matched would be
api/invoices?matchingStatus=Fully&matchingType=Man

And automatically matched 
api/invoices?matchingStatus=Fully&matchingType=Auto
