### ISSUE TITLE
Add action panel to All invoices view (DEMO)

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#305]
The action panel should have this components:
- Predefined views combo box with items: 

1.  All invoices (this is selected by default when entered to All invoices view),
2. Fully matched
3. Fully manual matched
4. Fully automatic matched 
Aappo should think about better/more correct terms for these.

- Open button
- Matching button 

----------------------------------------

**Comment by TimoRiippa** [comment]
Päivi will place the UX design to Google Drive, you will get the link via email

**Comment by pirttpi1** [comment]
Combo box is working fine! I don't have any automatically matched invoices, so I'll test a little bit more later (after text changes and translations)

**Comment by pirttpi1** [comment]
This is ok.
