### ISSUE TITLE
Open posting optimized view from the All invoice view (DEMO)

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#307]
User selects one invoice row from the All invoices view and presses Open button to see posting optimized view:

User can see posting data grid with posting data on the top and invoice image at the bottom.
There should a horizontal splitter between posting data grid and invoice image area.

On top of the view user can see action panel where he/she can see:
- Left arrow button back to the All invoices view
- Supplier name
- Placeholders for showing/hiding data i.e. Image, details, Posting (details aren't mandatory to be implemented at this point, in other words data cards)

See more precise UX design from Google Drive.

**Comment by pirttpi1** [comment]
User does not know which buttons are 'selected' (image/details/posting).
If user has posting and image: image does not have scroll bar, so only part of it is shown.

**Comment by jluukka** [comment]
From issue #332 comments: "When Details is opened as well, there should be scroll, because otherwise user might not see all the data cards."

**Comment by pirttpi1** [comment]
This works now ok, details related scroll will be checked later, when we know how the details are going to look like in 'final version'.
