### ISSUE TITLE
Open matching data from All invoices view (DEMO)

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#308]
User selects one invoice row from the All invoices view and presses Matching button to see Matching items.

When the invoice is fully matched then Matched view is shown, if the invoice is partially matched or PO invoice without matching started then Unmatched view is shown.

Only Matching user rights having user should have access to matching via this functionality (in test case Mark, but no Indy or Andy).

**Comment by pirttpi1** [comment]
User opens the invoice which has matching rows (for example fully matched).
Then user opens the next invoice and selects matching -> he sees the information of previous invoice. He can also match/unmatch rows, which means that he changes other invoice's information.

**Comment by pirttpi1** [comment]
I think this should be added:
This can be handled so that if invoice has no PO number -> matching button is disabled.

**Comment by pirttpi1** [comment]
Andy and Indy do not have user rights for matching -> user sees the 'disabled' icon, but can however open the matching, if he clicks it.

**Comment by pirttpi1** [comment]
Button related links are corrected in another issue. Otherwise this is ok.
