### ISSUE TITLE
Show invoice image in Matching views (both unmatched and matched) (DEMO)

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#309]
Add possibility for a user to see  invoice image also when he/she is doing the manual matching process or viewing the result.

Add splitter between invoice image matched/unmatched data grid.

Add also Image placeholder button to action panel (right most) for showing and hiding the invoice image part.

More about UX design in Google Drive.

**Comment by TimoRiippa** [comment]
When coming from All invoices to matching then left arrow button should direct also back to the All invoice s view and the opened invoice should be the selected one from the invoice data grid.

**Comment by pirttpi1** [comment]
when matching view is opened, the scroll needs to be added to 'image part' , so user can scroll the whole image.

**Comment by huukias** [comment]
Made an issue for the scrollbar issue 
https://github.com/OpusCapita/invoice/issues/351

**Comment by pirttpi1** [comment]
Add splitter between invoice image matched/unmatched data grid is not working. @Riippa should we do that, or is current enough?

**Comment by TimoRiippa** [comment]
Splitter is needed there, but I suppose Ilkka L. was working with that already.

**Comment by pirttpi1** [comment]
Splitter is working, id you are so quick that you find it before pdf is loaded. (so maybe it needs something more)

**Comment by ilkkalehtinen** [comment]
The PDF element messes up the splitter. There doesn't seem to be any quick solution to this.

**Comment by pirttpi1** [comment]
This is ok for now.
