### ISSUE TITLE
Create Postings/PostingItems for Imported POs/INVs (DEMO)

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#310]
**Descriptions**
During PO import:
* Create Posting (BusinessObjectClass - MatchingDocument, BusinessObjectId - PO number)
* For Each purchase order item create posing item
* For poItem.glAccount - create new glAccount/add existing glAccount
* for poItem.costDistribution - find position with with COSCENTER type - create new costCenter/add to posting item existing one
* copy poItem. ProductDescShort to posingItem.description
* copy corresponding fields (like grossAmount, netAmount, etc) from POitem to posting item

After Fully automatic matching for invoice - find corresponding posting and duplicate it for created invoice (change business object class and id)

**Comment by pirttpi1** [comment]
Posting lines are imported with GL account and cost center. VAT code is still missing.

**Comment by pirttpi1** [comment]
When PO:s are imported from eproc and invoice is fully matched, invoice is created and posting values are added correctly to amounts, GL account, cost center and VAT code.
