### ISSUE TITLE
Fully matched invoices should be removed from Matching views invoice list (DEMO)

### ISSUE THREAD

**Issue by TimoRiippa** [OpusCapita/invoice#311]
Only partially or non-matching started PO invoices should be shown in the invoice list of the matching functionality.

Fully matched invoices must be opened through All invoices view.
When manually matched invoice is totally matched and left arrow button is pressed for coming back to invoice list then this invoice is removed from the list and the next invoice in order is selected from the list.

**Comment by pirttpi1** [comment]
Only partially or non-matching started PO invoices should be shown in the invoice list of the matching functionality.  -> OK
Fully matched invoices must be opened through All invoices view. -> OK
When manually matched invoice is totally matched and left arrow button is pressed for coming back to invoice list then this invoice is removed from the list and the next invoice in order is selected from the list.  -> OK
