### ISSUE TITLE
'Optional comment' should be 'Mandatory comment', when comment is mandatory.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#314]
This should be changed in Clarification, Comment (and reject, when we get it).

**Comment by dzhitomirsky-sc** [comment]
Done. Please check it out.

**Comment by pirttpi1** [comment]
This is ok now! It needs translation, so I assign this to Aappo.

**Comment by pirttpi1** [comment]
Translation is ok as well.
