### ISSUE TITLE
Implement automatic attachments adding during eProc invoice import

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#329]
**TODO**
* use the latest user service version
* oci bash integrated script was updated to upload both cml's and pdf's to data-hub
* update eproc-sync to download not only cml file, but also attachments
* after successful invoice import - use blob-service client to upload attachment for newly created invoice.

**Comment by pirttpi1** [comment]
This works ok in production. Just select the products, proceed and make an order, and wait.

**Comment by alevchuk-sc** [comment]
We should load and unzip archives containing invoice cml and attachment files within a single iteration of proc-sync process as opposed to loading them file by file to prevent data loss.

**Comment by alevchuk-sc** [comment]
Updated. Invoices and attached pdf files are imported directly from zip archive.
Please test invoice import on dev environment.

**Comment by pirttpi1** [comment]
PO flip to invoice -> attach pdf file(s) -> invoice booking -> export
It works ok.
