### ISSUE TITLE
If there's a lot of posting lines, there should be scroll bar

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#331]
The scroll bar should be under posting dimension names (titles), not for the whole view. Now if I have a lot of posting lines, all the titles are eventually hidden, if you try to make posting to the last lines.

**Comment by pirttpi1** [comment]
The problem is with Firefox, because Chrome AND IE seem to work just fine.

**Comment by ilkkalehtinen** [comment]
Fixed on posting side.
