### ISSUE TITLE
All invoices - styles (DEMO)

### ISSUE THREAD

**Issue by jluukka** [OpusCapita/invoice#332]
Some style issues to be fixed:
- Actions panel border to follow the style laid out e.g. in matching view
- Add padding around the table of invoices (again, refer to the tables in matching)

**Comment by pirttpi1** [comment]
Scroll should be added under titles (Company name / supplier name /Due date). So user can scroll all his invoices without losing the links/headers.

**Comment by pirttpi1** [comment]
When Details is opened as well, there should be scroll, because otherwise user might not see all the data cards.

**Comment by jluukka** [comment]
Details pane scroll fixes will be handled in issue #307.

**Comment by pirttpi1** [comment]
This is not ok yet.
Actions panel border to follow the style laid out e.g. in matching view

**Comment by pirttpi1** [comment]
Yes, it was ok. the browser had old version in cache.
