### ISSUE TITLE
Updated product name, and tab items in navigation panel (DEMO)

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/invoice#338]
Product name: Invoice Process Automation
Tab items:
- My invoices
- Invoices overview
- Matching
- Analytics
- Archive
- Settings

See document  https://docs.google.com/a/opuscapita.com/presentation/d/1nbhXlSOKUiNk2OvvOjAUFF_Y2DWpTuXM9Eh9QSpHb94/edit?usp=sharing

**Comment by pirttpi1** [comment]
Links are shown as in specification.
