### ISSUE TITLE
Put new content to Settings navigation page (DEMO)

### ISSUE THREAD

**Issue by paiviheino** [OpusCapita/invoice#341]
Thus, former GitHub issue Make setting navigation view  (#312) is igrored
See document  https://docs.google.com/a/opuscapita.com/presentation/d/1nbhXlSOKUiNk2OvvOjAUFF_Y2DWpTuXM9Eh9QSpHb94/edit?usp=sharing

**Comment by pirttpi1** [comment]
This is ok now -> there's however more changes to come.
