### ISSUE TITLE
Add approval restrictions depending on user roles

### ISSUE THREAD

**Issue by alevchuk-sc** [OpusCapita/invoice#35]
Add the following restrictions to the invoice approval flow:
- For customer-assigned user execute search only for invoices assigned to this exact customer;
- Show available approval actions depending on user role. Add condition to approval flow scheme for approve and inspect events that checks if user has a corresponding role ('invoice-approver', 'invoice-inspector').

**Comment by dzhitomirsky-sc** [comment]
Done & merged.
