### ISSUE TITLE
Scrollbars not working for pdf images

### ISSUE THREAD

**Issue by huukias** [OpusCapita/invoice#351]
There is an issue with split-pane.

If there is an image, image does not have scroll bar. If the image does not fit into the page, only part of it is shown.

This issue affects at least to posting optimized, matched and unmatched view.

**Comment by ilkkalehtinen** [comment]
This is not an optimal solution, but this will give us scroll bar. Further study is needed to get the PDF rendering working properly with split pane.

**Comment by pirttpi1** [comment]
Now scroll works ok on 
* matching (unmatched and matched)
* invoices overview (open/unmatched/matched)
