### ISSUE TITLE
Import invoices/PO items needs to be possible for testing purposes.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#382]
Import invoices/PO items needs to be possible for testing purposes.

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 Import is now available on dev.

**Comment by huukias** [comment]
Should work with "/invoice/import/invoices" and "/invoice/import/matching"

**Comment by pirttpi1** [comment]
Links are now working ok.
