### ISSUE TITLE
'Blob' service research

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#39]
Research how to use *blob* service.
According to @gr4per there are examples in
> blob - examples of usage in onboarding (campaign editor and email rendering email extra files, landing page files, einvoice-send is getting terms and conditions)

Check out the services that already use _blob_ services for howTo configuration. In case of unresolvable issues contact @kwierchris for help.

When the service is up find out how to proceed with IO operations: find out how to  add customer specific file and then get. There is a library, called [blob-client](https://github.com/OpusCapita/blob-client), may be this will be helpful.

When you will deal with IO, contact @apechenko-sc and discuss PurchaseInvoice2Document model to store PurchaseInvoiceRelated  docs.

P.S. Do all stuff on _feature/blob-integration_ branch
P.P.S. Document the research progress steps for teammates

**Comment by kwierchris** [comment]
Two different examples on client side.
* Using form data:
https://github.com/OpusCapita/einvoice-send/blob/develop/src/client/components/ServiceConfigFlowPdf/ServiceConfigFlow3.js#L78-L82

* Using pure binary:
https://github.com/OpusCapita/onboarding/blob/develop/src/client/components/TemplateDropzone.react.js#L52-L73

The blob-client is only useful on the server side.

**Comment by dzhitomirsky-sc** [comment]
@kwierchris , thanks for examples
