### ISSUE TITLE
Add possibility to reject invoice on each step of approval flow

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#42]
*INTRO:*
Add possibility to reject invoice on each step of approval flow. It should be also possible to rollback rejection to previous step.

*TODO:*
* modify approval workflow schema to have available 'reject' events from _approvalRequired_ and _archived_. _Reject_ should roll back the transition to *one* step
* change *approvalRequired* _-(*approve*)->_ *approved*
* Rejection from _approvalRequired_ should be available for _inspector_ and _approver_
* Rejection from approved should be available for  _approver_  
* Modify *hasRole* guard to *hasRoles* (with required logic changes)

**Comment by dzhitomirsky-sc** [comment]
Done.

**Comment by apechenko-sc** [comment]
The idea was to introduce new statuses 'inspection rejected' and 'approval rejected'. Rollback from these statuses should be supported as well.

**Comment by dzhitomirsky-sc** [comment]
On current step it is not actual.
