### ISSUE TITLE
Add invoice details widgets

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#46]
**INFO**
As far as we have a UI mockup with nice looking invoice details, lets implement detail widgets that use back-end data that we already can provide.
<img width="1440" alt="details" src="https://user-images.githubusercontent.com/24650360/28860655-257c7e8c-7766-11e7-8bca-cd1fd3d1b9a6.png">

*TODO:*
* use [react-cards](https://github.com/OpusCapita/react-cards) extracted from oc-common-ui
* Implement Supplier, Totals and Attachments cards 
* replace current Invoice Details tab content with these cards

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 ,

Questions:
---------------------------------------------------------------------------------
*Totals Card*:
* We do not have any info about conversion rates, provided by iso-data service

*Supplier Info*:
* There is no info about specifier provided by supplier service (and what exactly is supplier specifier?)
* Supplier might have multiple bank accounts, which one should be displayed?
May be we should try to get bank account with the same countryId as the customer, assigned to current user? Now the first one is displayed.
* There are endpoint that provide information about supplier's addresses and contacts - should we display them?

**Comment by pirttpi1** [comment]
It seems the rate is not shown now, so we have to live with it.

We should show the bank account, which is attached for the invoice (in import). For now it can be the first one. (Country code does not help, because there can be like four Finnish accounts.)
We don't show supplier's address or contacts (and supplier specifier, which is just some extra information) in September's version. Supplier specifier is extra information for the supplier. The correct fields will be checked by Tommi later.

**Comment by pirttpi1** [comment]
User should be able to open the attachment in Attachment card (for example open excel file with Excel)

**Comment by pirttpi1** [comment]
One more thing: If there are no attachments, the text in the attachment card should be:
'There are no files attached to the invoice.'

**Comment by dzhitomirsky-sc** [comment]
* Added ability to download invoice attachments from DataCard
* Increased supplier card default height
* Fixed messages: 'Cancel Status', 'Comment Only' -> 'Cancel status', 'Comment only'

Please check it out again.

**Comment by pirttpi1** [comment]
Added ability to download invoice attachments from DataCard  => ok, pdf:s are opened correctly.
    Increased supplier card default height  => ok
    Fixed messages: 'Cancel Status', 'Comment Only' -> 'Cancel status', 'Comment only'  => ok

**Comment by pirttpi1** [comment]
Everything else was fine, but this one:
One more thing: If there are no attachments, the text in the attachment card should be:
'There are no files attached to the invoice.'

**Comment by dzhitomirsky-sc** [comment]
Fixed message.

**Comment by pirttpi1** [comment]
Now these are right.

**Comment by dzhitomirsky-sc** [comment]
Closed.
