### ISSUE TITLE
Add mandatory commenting for several workflow points

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#48]
**INFO**
On certain workflow steps we need an ability to make comment mandatory (user should have no ability to send event with empty commentary field).

**TODO**
* add comment existence check into action and throw exception wth in case comment is null or empty.
* catch this error on event sending and mark textarea with 'has-error' if exceptions has message 'comment should not be null'
* events with mandatory comments: _sendToClarification, rejection, sendComment_

**Comment by pirttpi1** [comment]
Comment should be mandatory on 'set to clarification'/'add comment' (and reject, when it's implemented)

**Comment by dzhitomirsky-sc** [comment]
@alevchuk-sc Make Action component optionally configurable for support mandatory navigation.
If no required comment provided text-area should become red (has-error class) and warning alert should be show (think about some reasonable message.)

**Comment by pirttpi1** [comment]
Comment should be mandatory in:; sendToClarification, rejection, sendComment
Now 'Cancel review' and 'Cancel approval' need the comment as well -> need to be corrected.

**Comment by pirttpi1** [comment]
After corrections it works ok, so
Approval/Review / cancel approval/review/clarification -> comment optional
Clarification / comment -> comment mandatory
