### ISSUE TITLE
Application doesn't work under IE

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#59]
Error message appears in console when trying to access application.
> Object doesn't support property or method 'resolve'

**Comment by dzhitomirsky-sc** [comment]
Fixed. Please check for IE.

**Comment by pirttpi1** [comment]
At least for me, invoice images are not opening, just initializing.

**Comment by pirttpi1** [comment]
I have to check this more, it's not IE related problem.

**Comment by pirttpi1** [comment]
Ok, I can open Paris with IE,, there's some problems with showing the images (when there's no image), but this will be checked later.
