### ISSUE TITLE
'My Tasks' view enhancement

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#61]
**Intro**
When the invoice is inspected by inspector or approved by approver it should be removed from 'My Tasks' view.

**Details**
Modify _filter_ function of _MyTaskView_ data handler in a way not to display invoices with 'approvalRequired' status for inspector and 'approved' status for approver. 'cancel inspection/approval' event should be available only from 'Processed view'.

**Comment by dzhitomirsky-sc** [comment]
Done. Please check it out.

**Comment by pirttpi1** [comment]
When inspector inspects the invoice, it it removed from My Tasks List, as is shown on the Processed list.
The same thing when the approver approves the invoice.
If approver/inspector cancels the invoice, it's back on My Tasks list.
