### ISSUE TITLE
Approval workflow modification

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#62]
**TODO**
* Make commenting available on each step of the invoice approval
* Only 'inspector' should be able to cancel inspection

**PS**
Check that invoices displayed on 'My Tasks' and 'Processed' stay consistent:

_MyTasks_:
* inspector: inspection required, inspector clarification required
* approver: approval required, approver clarification required

_Processed_
* inspector: invoices with _inspectedBy_ field equal to inspector's user ID
* approved: invoices with approvedBy_ field equal to inspector's user ID

**Comment by dzhitomirsky-sc** [comment]
Please check it out.

**Comment by pirttpi1** [comment]
@alevchuk-sc: When approver approves the invoice, which passed the inspection automatically -> inspector sees the invoice in 'my Tasks list'. He should not see.

    Make commenting available on each step of the invoice approval  -> ok
    Only 'inspector' should be able to cancel inspection  -> ok

**Comment by alevchuk-sc** [comment]
Updated. Please test.

**Comment by pirttpi1** [comment]
This one doesn't work correctly,
Processed
    **inspector: invoices with inspectedBy field equal to inspector's user ID**
    approved: invoices with approvedBy_ field equal to inspector's user ID

Now the inspector sees the invoices which are automatically inspected, not by this inspector.
(User should be able to see only his own invoices, nothing else).

**Comment by pirttpi1** [comment]
TODO
•	Make commenting available on each step of the invoice approval -> ok
•	Only 'inspector' should be able to cancel inspection  -> ok (and at this moment only when the approval is not yet done)
MyTasks:
•	inspector: inspection required, inspector clarification required  -> ok
•	approver: approval required, approver clarification required  -> ok
Processed
•	inspector: invoices with inspectedBy field equal to inspector's user ID  -> ok, inspector sees the invoices which he had inspected (approved or not)
•	approved: invoices with approvedBy_ field equal to inspector's user ID -> ok, approver sees the approved invoices.

**Comment by dzhitomirsky-sc** [comment]
Done.
