### ISSUE TITLE
UI adjustments

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#63]
**TODO**
* Change _Action.tab.rejectApproval_ & _Action.tab.rejectInspection_ messages to 'Cancel Status'
* Uncapitalize the second word in _Action.event.rejectInspection_ & _Action.event.rejectApproval_
* Change _Action.headerLabel_  message to 'Optional comment'
* Change _TaskItem.customerId_  message to 'Payer Company'
* Change _Action.event.sendToClarification_ message to 'Set to Clarification'
* Change _TaskItem.status.inspClrRequired_ and _TaskItem.status.appClrRequired_ to 'Clarification Required'
* Make commenting textarea size 1 row by default
* Modify _EmptyLayout_ component to take message as property and add message for empty 'Processed' view - 'At the moment you don't have any processed invoices'
* Enhance commenting - under the textarea add _n/2000_ counter that should increase after every new symbol added e.g. 0/2000 -(comment == 'a')> 1/2000 -(comment == 'aaa')> 3/2000 e.t.c. When the string value exceeds db field length textarea should react no more on new symbols adding. 

**PS**
After modifying/adding all labels please ask @apolishchuk-sc or @amotuz-sc to give you proper german translations.

**Comment by dzhitomirsky-sc** [comment]
Please add _shoudlComponentUpdate_ for empty layout that return true in case 
```javascript
nextContext.i18n.locale !== this.context.i18n.locale
```

**Comment by dzhitomirsky-sc** [comment]
Done. Please check it out.

**Comment by pirttpi1** [comment]
These are ok:
    Change Action.tab.rejectApproval & Action.tab.rejectInspection messages to 'Cancel Status'  => ok
    Uncapitalize the second word in Action.event.rejectInspection & Action.event.rejectApproval  => ok
    Change Action.headerLabel message to 'Optional comment'  => ok
    Change TaskItem.customerId message to 'Payer Company'  => ok
    Make commenting textarea size 1 row by default => ok
    Modify EmptyLayout component to take message as property and add message for empty 'Processed' view - 'At the moment you don't have any processed invoices' -> ok
    Enhance commenting - under the textarea add n/2000 counter that should increase after every new symbol added e.g. 0/2000 -(comment == 'a')> 1/2000 -(comment == 'aaa')> 3/2000 e.t.c. When the string value exceeds db field length textarea should react no more on new symbols adding.  => ok

These need some clarification:
    Change Action.event.sendToClarification message to 'Set to Clarification' 
    Change TaskItem.status.inspClrRequired and TaskItem.status.appClrRequired to 'Clarification Required'

**Comment by pirttpi1** [comment]
These should be changed:
Set to Clarification -> Set to clarification
Approval/Inspection/Clarification Required -> Approval/Inspection/Clarification required

**Comment by dzhitomirsky-sc** [comment]
@alevchuk-sc Please do the required changes.

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 please check out uncapitalized translation.

**Comment by pirttpi1** [comment]
These are now ok:
Set to Clarification -> Set to clarification
Approval/Inspection/Clarification Required -> Approval/Inspection/Clarification required
