### ISSUE TITLE
Add optional automatic inspection

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#64]
**Info**
In case _invoice.grossAmout_ < 200 we need to implement automatic inspection. 

**TODO**
Implement additional invoice node with automatic inspections it will look very similar to

```javascript
    {
      "from": "inspectionRequired",
      "event": "automatic-inspect",
      "to": "approvalRequired",
      "automatic": true
      "guards": [
        {
          "name": "isLessThan",
          "arguments": {
             "field": "grossAmout",
            "amount": 200
          }
        }
      ]
    }
```
**PS**
Add corresponding guard and tests for it.  Cover new workflow node with unit tests. Please check that auto-inspection work correct importing invoice with gross price less than 200 eur.

**Comment by dzhitomirsky-sc** [comment]
* Disable manual _inspect_ transition in case grossAmount < 200 (introduce new guard isGreaterOrEqual)
* enhance logic  of /transitions endpoint to provide info only about _manual_ available transitions.

**Comment by dzhitomirsky-sc** [comment]
Done.

**Comment by pirttpi1** [comment]
When invoice gross amount is > 200, it needs inspection. When it's less, does not need, and goes directly to approval. -> OK. 
I imported two invoices, the other one was 201, the other one 199 -> Worked just fine.
