### ISSUE TITLE
Improve comments handling

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/invoice#68]
When inspector or approver adds a comment, we should save not only text, but also its author and timestamp and event when it was provided.
Currently this information will be stored in  field `commentary` in JSON format. In future it will be replaced with a dedicated structure. 
Comments must be displayed in corresponding data card on Details tab.
![comments](https://user-images.githubusercontent.com/24652264/29308542-ea33b7e8-81ae-11e7-89e1-584322a0bb54.png)

**Comment by pirttpi1** [comment]
User should not be able to add comment more than 2000 chars (limitation). -> Validation needs to be there.

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 2000 symbmols restrictions is being done on #63 .

**Comment by dzhitomirsky-sc** [comment]
Implemented commenting is done _only_ for demo purposes - message history is saved as json string into the PurchaseInvoice.commentary field. 2000 symbols counter is fake now - it counts only number of current comment is textarea and if string value in db will exceed it - widget will be broken - so please don't wring novels inside comment area during demo :)
When comment is posted - is is displayed inside data card with status badge in case comment was posted with some even and with 'text' badge in case of 'Comment only'. We will refactor this approach ASAP when we will have commenting db structure onboard.

**Comment by pirttpi1** [comment]
explained problems to Daniel. He will check a little bit more. (So if no comment -> no line on 'comments' card)

**Comment by dzhitomirsky-sc** [comment]
Should also make comment sorting.

**Comment by dzhitomirsky-sc** [comment]
Fixed next points:
* added comment sorting by date
* fixed status displaying
* added error handling in case of too long comment

**Comment by pirttpi1** [comment]
This is ok for this September version.
