### ISSUE TITLE
Add sorting

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#85]
We need an ability to add sorting field at the top of TaskItemList.
Check out the Ui mockUp:
<img width="1440" alt="2017-08-22 13 47 43" src="https://user-images.githubusercontent.com/24650360/29562073-8e801d82-8740-11e7-9888-cd1291e641b3.png">
There is already a _SortInvoice_ component provided by @ilkkalehtinen try to reuse it. In case of any troubles contact him directly.

Sorting fields should be:
* Due Date
* Supplier
* grossAmmount

As far as we don't have any paging or search functionality and all invoices are loaded to ui -
implement sorting logic on ui.

**Comment by dzhitomirsky-sc** [comment]
Added sorting, please test it.

**Comment by pirttpi1** [comment]
When sorting is done, the correct invoice should be loaded as well. Now the wrong invoice is shown on the right side.

**Comment by alevchuk-sc** [comment]
Updated. When sorting value is changed selection jumps to the first invoice in the list. Please test.

**Comment by pirttpi1** [comment]
This is ok now.
