### ISSUE TITLE
Move commenting away from workflow process

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/invoice#86]
**Motivation**
As far as commenting is available for everyone the workflow logic being duplicated on ui to restrict search result for 'MyTasks' and 'Processed' views.

**TODO**
* Implement 'Comment' with it's own logic that posts comment for current invoice.
* Remove 'commentOnly' steps from workflow definition
* Adjust unit tests after it
* Add endpoint for adding comments
* Add required logic for TaskDataHandler's filter & fetchers.

**Comment by alevchuk-sc** [comment]
Implemented. Please test that comments are posted properly.

**Comment by pirttpi1** [comment]
If I add just the comment, at least I have problems. It seems that if I change the invoice to the next one, it is not loaded to the ui and 'Comment'-icon is not updated either. After changing My list to processed and back, everything works ok, until I add next comment.

**Comment by alevchuk-sc** [comment]
Was broken by other issue implementation. Now it's fixed. Please test.

**Comment by pirttpi1** [comment]
Now commenting works again. There's still optional/mandatory missing, but it comes later.
