### ISSUE TITLE
Invoice is <200 EUR ->approver sets it to clarification, inspector sees the invoice.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#88]
There's invoice with 199 EUR (automatic inspection)
The approver sets invoice to clarification. Only he should see the invoice in 'My tasks', but now the inspector sees it too.

**Comment by alevchuk-sc** [comment]
Fixed. If invoice needs clarification for approval only approver can see it in my tasks.
Please test.

**Comment by pirttpi1** [comment]
This is ok now.

**Comment by dzhitomirsky-sc** [comment]
Closed.
