### ISSUE TITLE
All status icons should be removed, but 'in clarification' '?'

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#94]
Now there are a lot of icons, but in the demo version we want to show only 'in clarification' '?'

**Comment by pirttpi1** [comment]
Icon in #96 should be there as well as 'in clarification'

**Comment by dzhitomirsky-sc** [comment]
@pirttpi1 it is not totally clear which icons should stay and which should removed. Please, add more details.

**Comment by pirttpi1** [comment]
In clarification and commented.  Nothing else,

**Comment by alevchuk-sc** [comment]
Updated. Please test.

**Comment by pirttpi1** [comment]
This is ok now.
