### ISSUE TITLE
User selects the invoice and approves it, the next invoice should be selected active, not the first one.

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#98]
User selects the third invoice and approves it.
(Invoice is not shown in my task anymore ->shown in processed.)
The next invoice on my task list should be selected, not the first one.
When user is in the last invoice and approves/reviews it (so that it's remove from the my task list), the previous invoice is selected.

**Comment by alevchuk-sc** [comment]
Implemented. Please test.

**Comment by pirttpi1** [comment]
Now this works like described.
