### ISSUE TITLE
Totals card modifications

### ISSUE THREAD

**Issue by pirttpi1** [OpusCapita/invoice#99]
Order should be:
Gross amount
Net amount
VAT amount
Currency code (3 chars, like EUR)

**Comment by alevchuk-sc** [comment]
Updated. Please test.

**Comment by pirttpi1** [comment]
Please change the titles like in this issue. (And also check the titles in supplier card (Supplier Code -> Supplier code and so on)

**Comment by alevchuk-sc** [comment]
Updated for supplier and total cards. Please test.

**Comment by pirttpi1** [comment]
This is ok now.

**Comment by dzhitomirsky-sc** [comment]
Closed.
